### ISSUE TITLE
Passing a non-string value to unquote function is deprecated

### ISSUE THREAD

**Issue by mzgajner** [astina/yy#19]
Since SASS 3.4.10, there is a warning about the use of `unquote` function in the console. It is currently used in [_responsive-font.scss](https://github.com/astina/yy/blob/master/sass/font/_responsive-font.scss#L110) to remove quotes when parsing values from the `fonts.scss` configuration file. In future versions of SASS, the function will return an error if a non-string value is passed.

Because of that, we simply have to check if the value is a string before calling `unquote` on it. I added a [simple PR](https://github.com/astina/yy/pull/20) with the solution.

**Comment by benib** [comment]
cool, thanks. merged the PR.
